# Metadata
title: "Gallium Wang's Site"
description: "Iâ€™m an interactive web developer, designer, and storyteller. Here's something interesting I worked on!"
keywords: ["programming", "jekyll","blog","GalliumWang"]
domain: "https://galliumwang.com"

# Third party services
# (Anything you put here will be public!)
google-analytics:
github: "GalliumWang"
branch: "glitch"
github_source: "GalliumWang"

# Rubygems
# (The ones used for this site breaks GitHub Pages)
plugins:
  - jekyll-archives
  - jekyll-default-layout
  - jekyll-auto-image
  - jekyll-postfiles

# Build settings
encoding: utf-8
markdown: kramdown
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"

# Permalinks
permalink: /:title/

# Tags
jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tag: '/hashtag/:name/'
